# Generated by Django 4.2.3 on 2023-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('count', models.IntegerField()),
                ('cost', models.FloatField()),
                ('pic', models.ImageField(upload_to='shop/static/image')),
            ],
        ),
    ]
